fix nopull arg; dont refuse to generate CA if certutil absent

diff --git a/bin/generate-ca b/bin/generate-ca
--- a/bin/generate-ca
+++ b/bin/generate-ca
@@ -2,12 +2,6 @@
 # This shell script will generate an X509 certificate for your proxy
 #
 
-if ! which certutil > /dev/null
-then
-    echo "'certutil' command not found. Please install it."
-    exit 1
-fi
-
 if ! which openssl > /dev/null
 then
     echo "'openssl' command not found. Please install it."
@@ -57,6 +51,13 @@ echo "=> Please import it into your browser!                              "
 echo "=> NOTE: This CA certificate is generated.                          "
 echo "=> It only exists on YOUR computer                                  "
 echo "======================================================================"
+
+if ! which certutil > /dev/null
+then
+    echo "'certutil' command not found. No automatic import of CA."
+    exit 0
+fi
+
 
 echo "This utility can also add your newly generated CA certificate to the trust stores of Chrome and Firefox. Do you want to allow this?"
 echo -n "(Y/n) "
