refactored reclaim helper

diff --git a/reclaim b/reclaim
--- a/reclaim
+++ b/reclaim
@@ -6,33 +6,140 @@ RED='\033[0;31m'
 GREEN='\033[0;32m'
 REC='\033[1;34m'
 NC='\033[0m'
+NO_PULL=0
+DEMO_ENABLED=0
+DOCKERFILE="config/docker-compose.yml"
+CUSTOM_DOCKERFILE=0
+ACTION="none"
+NOARG=1
 
-startup() {
+parse_opt() {
+    while [[ $# -gt 0 ]]
+    do
+        NOARG=0
+        key="$1"
+        case $key in
+            -n|--no-pull)
+                NO_PULL=1
+                shift
+                ;;
+            -d|--demo)
+                DEMO_ENABLED=1
+                DOCKERFILE="config/docker-compose_demo.yml"
+                shift
+                ;;
+            -f|--dockerfile)
+                DOCKERFILE="$2"
+                CUSTOM_DOCKERFILE=1
+                shift
+                shift
+                ;;
+            start)
+                ACTION="start"
+                shift
+                ;;
+            stop)
+                ACTION="stop"
+                shift
+                ;;
+            purge)
+                ACTION="purge"
+                shift
+                ;;
+            restart)
+                ACTION="restart"
+                shift
+                ;;
+            *)
+                reclaim_banner
+                echo -e "${RED}Unknown argument:${NC} $key\n"
+                reclaim_usage
+                exit 1
+                shift
+                ;;
+        esac
+    done
+
+    if [[ $CUSTOM_DOCKERFILE = 1 && $DEMO_ENABLED = 1 ]];
+    then
+        echo -e "${RED}WARNING: demo was enabled and custom Dockerfile set. This is currently NOT supported."
+        echo -e "Not starting demo, then.${NC}"
+    fi
+}
+
+stop_reclaim() {
+    reclaim_banner
+    echo "Shutting down $PROD"
+    if [ -f .tmp/compose ]
+    then
+        DOCKERFILE=`cat .tmp/compose`
+    fi
+    docker-compose -f $DOCKERFILE down
+
+    echo -e "reclaim stopped.\n"
+    reclaim_status
+}
+
+start_reclaim() {
+    reclaim_banner
+    echo "Starting $PROD..."
     # check whether cert has already been generated
     if ! docker run --rm -v reclaim-gnunet:/volume alpine ls /volume/gns/gns_ca_cert.pem &> /dev/null
     then
-      echo "\n"
-      echo "No CA cert found. Generating..."
-      if [ -f ./bin/generate-ca ]
-      then
-        ./bin/generate-ca
-      else
-        echo "Error... CA helper not found!"
-        exit 1
-      fi
+        echo "\n"
+        echo "No CA cert found. Generating..."
+        if [ -f ./bin/generate-ca ]
+        then
+            ./bin/generate-ca
+        else
+            echo "Error... CA helper not found!"
+            exit 1
+        fi
     else
         echo "gns certificate has already been added"
     fi
 
-    if [[ $2 != "--no-pull" ]]
+    # has user given preferences? always override
+    if [[ $CUSTOM_DOCKERFILE = 1 || $DEMO_ENABLED = 1 ]]
     then
-        docker-compose -f $1 pull
+        # store info about docker-compose file
+        mkdir -p .tmp
+        echo $DOCKERFILE > .tmp/composefile
+    else
+        # try to read an existing starting configuration
+        if [ -f .tmp/compose ]
+        then
+            DOCKERFILE=`cat ./tmp/compose`
+        fi
     fi
-    docker-compose -f $1 up -d
+
+    if [[ $NO_PULL ]]
+    then
+        echo "Not pulling images from Docker Hub"
+    else
+        docker-compose -f $DOCKERFILE pull
+    fi
+    docker-compose -f $DOCKERFILE up -d
+
+    echo -e "started.\n"
+    reclaim_status
 }
 
-purge() {
-    docker-compose -f $1 down --remove
+restart_reclaim() {
+    stop_reclaim
+    start_reclaim
+}
+
+purge_reclaim() {
+    echo "Purging $PROD"
+
+    if [ -f .tmp/compose ]
+    then
+        DOCKERFILE=`cat ./tmp/compose`
+        rm -rf .tmp
+    fi
+
+    docker-compose -f $DOCKERFILE down --remove
     echo "Do you also want to remove the named volumes (persistent data)?"
     echo -n "(Y/n) "
     read input
@@ -44,79 +151,78 @@ purge() {
     else
         echo "not removing named volumes"
     fi
-    exit 0
 }
 
-if [[ $1 = "stop" ]]
+reclaim_banner() {
+    echo -e "${REC}                     __      _         "
+    echo "   ________  _ _____/ /___ _(_)___ ___ "
+    echo '  / ___/ _ \(_) ___/ / __ `/ / __ `__ \'
+    echo " / /  /  __/ / /__/ / /_/ / / / / / / /"
+    echo "/_/   \___(_)\___/_/\__,_/_/_/ /_/ /_/ "
+    echo -e "                                       ${NC}"
+    echo "https://reclaim-identity.io"
+    echo "(C) 2018 Fraunhofer AISEC"
+    echo ""
+}
+
+reclaim_status() {
+    echo "Status:"
+    if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-runtime) 2>/dev/null` ]; then
+        echo -e "${RED}\xE2\x9D\x8C Service is not running.${NC}"
+    else
+        echo -e "${GREEN}\xE2\x9C\x94 Service is running.${NC}"
+    fi
+
+    if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-ui) 2>/dev/null` ]; then
+        echo -e "${RED}\xE2\x9D\x8C UI is not running.${NC}"
+    else
+        echo -e "${GREEN}\xE2\x9C\x94 UI is running.${NC}"
+    fi
+    echo ""
+}
+
+reclaim_usage() {
+    echo "Usage:"
+    echo "$0 start: starts $PROD"
+    echo "$0 stop: shuts $PROD down"
+    echo "$0 restart: restarts $PROD"
+    echo "$0 purge: shuts $PROD down and purges its data"
+    echo "the --no-pull (-n) flag can be used to prevent pulling images from remote"
+    echo "the --demo (-d) flag can be used to start a demo relying party"
+    echo "the --dockerfile (-f) flag can be used to specify a custom Dockerfile"
+}
+
+reclaim_full() {
+    reclaim_banner
+    reclaim_status
+    reclaim_usage
+}
+
+parse_opt "$@"
+
+case $ACTION in
+    none)
+        ;;
+    start)
+        start_reclaim
+        ;;
+    stop)
+        stop_reclaim
+        ;;
+    restart)
+        restart_reclaim
+        ;;
+    purge)
+        purge_reclaim
+        ;;
+    *)
+        echo "${RED}Unregistered Action. This should not happen.${NC}"
+        exit 1
+        ;;
+esac
+
+if [ $NOARG = 1 ]
 then
-    echo "Shutting down $PROD"
-    docker-compose -f config/docker-compose.yml down
+    reclaim_full
 fi
-
-if [[ $1 = "stop_demo" ]]
-then
-    echo "Shutting down $PROD"
-    docker-compose -f config/docker-compose_demo.yml down
-fi
-
-if ([[ $1 = "start_demo" ]] || [[ $1 = "restart_demo" ]])
-then
-    echo -n "Starting $PROD Demo..."
-    startup config/docker-compose_demo.yml $2
-    echo "started."
-fi
-
-if ([[ $1 = "start" ]] || [[ $1 = "restart" ]])
-then
-    echo -n "Starting $PROD..."
-    startup config/docker-compose.yml $2
-    echo "started."
-    exit 0
-fi
-
-if [[ $1 = "purge_demo" ]]
-then
-    echo "Purging $PROD demo"
-    purge config/docker-compose_demo.yml
-fi
-
-
-if [[ $1 = "purge" ]]
-then
-    echo "Purging $PROD"
-    purge config/docker-compose.yml
-fi
-
-echo -e "${REC}                     __      _         "
-echo "   ________  _ _____/ /___ _(_)___ ___ "
-echo '  / ___/ _ \(_) ___/ / __ `/ / __ `__ \'
-echo " / /  /  __/ / /__/ / /_/ / / / / / / /"
-echo "/_/   \___(_)\___/_/\__,_/_/_/ /_/ /_/ "
-echo -e "                                       ${NC}"
-echo "https://reclaim-identity.io"
-echo "(C) 2018 Fraunhofer AISEC"
-echo ""
-echo "Status:"
-if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-runtime) 2>/dev/null` ]; then
-  echo -e "${RED}\xE2\x9D\x8C Service is not running.${NC}"
-else
-  echo -e "${GREEN}\xE2\x9C\x94 Service is running.${NC}"
-fi
-
-if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-ui) 2>/dev/null` ]; then
-  echo -e "${RED}\xE2\x9D\x8C UI is not running.${NC}"
-else
-  echo -e "${GREEN}\xE2\x9C\x94 UI is running.${NC}"
-fi
-echo ""
-echo "Usage:"
-echo "$0 start: starts $PROD"
-echo "$0 start_demo: starts $PROD with one example relying party"
-echo "$0 stop: shuts $PROD down"
-echo "$0 stop_demo: shuts $PROD and demo down"
-echo "$0 restart: restarts $PROD"
-echo "$0 restart_demo: restarts $PROD and one example relying party"
-echo "$0 purge: shuts $PROD down and purges its data"
-echo "$0 purge_demo: shuts $PROD and demo down and purges their data"
-echo "the --no-pull flag can be used to prevent pulling images from remote"
 
