revert 20812c10f319f9db67592161dd48917b36e5151e

diff --git a/reclaim b/reclaim
--- a/reclaim
+++ b/reclaim
@@ -2,91 +2,114 @@
 
 PROD="reclaim"
 
-COMPOSE_FILE="config/docker-compose.yml"
-COMPOSE_FILE_DEMO="config/docker-compose_demo.yml"
-if [ -f config/demo_enabled ]
-then
-  COMPOSE_FILE=$COMPOSE_FILE_DEMO
-fi
-
-if [[ $1 = "update" ]]
-then
-  echo "Shutting down $PROD"
-  docker-compose -f $COMPOSE_FILE pull
-  exit 0
-fi
-
 if [[ $1 = "stop" ]]
 then
-  echo "Shutting down $PROD"
-  docker-compose -f $COMPOSE_FILE down
-  exit 0
+    echo "Shutting down $PROD"
+    docker-compose -f config/docker-compose.yml down
+    exit 0
 fi
+
+if [[ $1 = "stop_demo" ]]
+then
+    echo "Shutting down $PROD"
+    docker-compose -f config/docker-compose_demo.yml down
+    exit 0
+fi
+
 
 if [[ $1 = "restart" ]]
 then
-  echo "Restarting $PROD"
-  docker-compose -f $COMPOSE_FILE down
+    echo "Restarting $PROD"
+    docker-compose -f config/docker-compose.yml down
+fi
+
+if ([[ $1 = "start_demo" ]] || [[ $1 = "restart_demo" ]])
+then
+    echo -n "Starting $PROD Demo..."
+
+    # check whether cert has already been generated
+    if ! docker run --rm -v reclaim-gnunet:/volume alpine ls /volume/gns/gns_ca_cert.pem &> /dev/null
+    then
+      echo "\n"
+      echo "No CA cert found. Generating..."
+      if [ -f ./bin/generate-ca ]
+      then
+        ./bin/generate-ca
+      else
+        echo "Error... CA helper not found!"
+        exit 1
+      fi
+    else
+        echo "gns certificate has already been added"
+    fi
+
+    docker-compose -f config/docker-compose_demo.yml pull
+    docker-compose -f config/docker-compose_demo.yml up -d
+    echo "started."
+    exit 0
 fi
 
 if ([[ $1 = "start" ]] || [[ $1 = "restart" ]])
 then
-  echo -n "Starting $PROD"
+    echo -n "Starting $PROD..."
 
-  # check whether cert has already been generated
-  if ! docker run --rm -v reclaim-gnunet:/volume alpine ls /volume/gns/gns_ca_cert.pem &> /dev/null
-  then
-    echo "\n"
-    echo "No CA cert found. Generating..."
-    if [ -f ./bin/generate-ca ]
+    # check whether cert has already been generated
+    if ! docker run --rm -v reclaim-gnunet:/volume alpine ls /volume/gns/gns_ca_cert.pem &> /dev/null
     then
-      ./bin/generate-ca
+      echo "\n"
+      echo "No CA cert found. Generating..."
+      if [ -f ./bin/generate-ca ]
+      then
+        ./bin/generate-ca
+      else
+        echo "Error... CA helper not found!"
+        exit 1
+      fi
     else
-      echo "Error... CA helper not found!"
-      exit 1
+        echo "gns certificate has already been added"
     fi
-  else
-    echo "gns certificate has already been added"
-  fi
-  if ! [ -f config/initial_setup ]
-  then
-    if [ -f config/demo_enabled ]
-    then
-      rm config/demo_enabled
-    fi
-    echo "Do you want to setup the demo relying party?"
+
+    docker-compose -f config/docker-compose.yml pull
+    docker-compose -f config/docker-compose.yml up -d
+    echo "started."
+    exit 0
+fi
+
+if [[ $1 = "purge_demo" ]]
+then
+    echo "Purging $PROD demo"
+    docker-compose -f config/docker-compose_demo.yml down --remove
+    echo "Do you also want to remove the named volumes (persistent data)?"
     echo -n "(Y/n) "
     read input
-    if ! [ -z $input ] && [ $input = "Y" ]
+    if [[ $input = "Y" ]]
     then
-      touch config/demo_enabled
-      $COMPOSE_FILE=$COMPOSE_FILE_DEMO
+        echo "removing named volumes"
+        docker volume rm reclaim-gnunet || true
+        docker volume rm reclaim || true
+    else
+        echo "not removing named volumes"
     fi
-    touch config/initial_setup
-  fi
-  docker-compose -f $COMPOSE_FILE up -d
-  echo "started."
-  exit 0
+    exit 0
 fi
+
 
 if [[ $1 = "purge" ]]
 then
-  echo "Purging $PROD"
-  docker-compose -f $COMPOSE_FILE down --remove
-  echo "Do you also want to remove the named volumes (persistent data)?"
-  echo -n "(Y/n) "
-  read input
-  if [[ $input = "Y" ]]
-  then
-    echo "removing named volumes"
-    rm config/demo_enabled
-    rm config/initial_setup
-    docker volume rm reclaim-gnunet || true
-    docker volume rm reclaim || true
-  else
-    echo "not removing named volumes"
-  fi
-  exit 0
+    echo "Purging $PROD"
+    docker-compose -f config/docker-compose.yml down --remove
+    echo "Do you also want to remove the named volumes (persistent data)?"
+    echo -n "(Y/n) "
+    read input
+    if [[ $input = "Y" ]]
+    then
+        echo "removing named volumes"
+        docker volume rm reclaim-gnunet || true
+        docker volume rm reclaim || true
+    else
+        echo "not removing named volumes"
+    fi
+    exit 0
 fi
 
 echo "                     __      _         "
@@ -99,27 +122,23 @@ echo "https://reclaim-identity.io"
 echo "(C) 2018 Fraunhofer AISEC"
 echo ""
 echo "Status:"
-if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f $COMPOSE_FILE ps -q reclaim-runtime) 2>/dev/null` ]; then
+if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-runtime) 2>/dev/null` ]; then
   echo "* Service is not running."
 else
   echo "* Service is running."
 fi
 
-if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f $COMPOSE_FILE ps -q reclaim-ui) 2>/dev/null` ]; then
+if [ -z `docker ps -q --no-trunc | grep $(docker-compose -f config/docker-compose.yml ps -q reclaim-ui) 2>/dev/null` ]; then
   echo "* UI is not running."
 else
   echo "* UI is running."
 fi
-if [ -f config/demo_enabled ]
-then
-  echo "* Demo relying party is enabled."
-fi
 echo ""
-echo "Usage: $0 <option>"
-echo "Values for <option> are:"
+echo "Usage:"
 echo "$0 start: starts $PROD"
+echo "$0 start_demo: starts $PROD with one example relying party"
 echo "$0 stop: shuts $PROD down"
 echo "$0 restart: restarts $PROD"
-echo "$0 update: Update to latest version"
+echo "$0 restart_demo: restarts $PROD and one example relying party"
 echo "$0 purge: shuts $PROD down and purges its data"
 
